# Generated by Django 4.1.5 on 2023-02-08 18:44

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_client_fullname_client_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='')),
                ('description_given_on', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='date',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='noOfItems',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled Order'), (1, 'Placed Order'), (2, 'Shipped Order'), (3, 'Delivered Order')], default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order_updated_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='total_items_ordered',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderedItems', to='myapp1.client'),
        ),
    ]
