# Generated by Django 4.1.5 on 2023-02-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_description_remove_orderitem_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order_status',
            field=models.IntegerField(choices=[(0, 'Cancelled Order'), (1, 'Placed Order'), (2, 'Shipped Order'), (3, 'Delivered Order')], default=0),
        ),
    ]
